version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: my-backend:latest
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=${POSTGRES_DB}
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django_secret_key
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - database
    networks:
      - app_network
    secrets:
      - postgres_password
      - django_secret_key

  frontend:
    build:
      context: ./frontend
    image: my-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - app_network

  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    configs:
      - source: postgres_config
        target: /etc/postgresql/postgresql.conf
    networks:
      - app_network
    secrets:
      - postgres_password

volumes:
  pgdata:

networks:
  app_network:

secrets:
  postgres_password:
    file: ./secrets/postgres_password
  django_secret_key:
    file: ./secrets/django_secret_key

configs:
  postgres_config:
    file: ./configs/postgres-config.conf
