version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: admin               # Utilisateur de la base de données
      POSTGRES_PASSWORD: admin # Mot de passe de l'utilisateur
      POSTGRES_DB: mydatabase            # Base de données par défaut
    volumes:
      - docker_pgdata:/var/lib/postgresql/data # Volume pour la persistance des données
    networks:
      - docker_app_network

  backend:
    build: ./backend
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - database
    networks:
      - docker_app_network

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - docker_app_network

networks:
  docker_app_network:  # Définir un réseau pour la communication entre les conteneurs
    driver: bridge

volumes:
  docker_pgdata:  # Volume pour stocker les données PostgreSQL
